version: '3.3'

services:
  deep_thoughts_webserver:
    build: webserver
    container_name: deep_thoughts_webserver
    image: deep_thoughts
    restart: on-failure
    ports:
      - 80:7777
    volumes:
      - ./private:/app/private
  deep_thoughts_monitor:
    build: monitor
    container_name: deep_thoughts_monitor
    image: deep_thoughts_monitor
    restart: on-failure
    ports:
      - 7778:7778
    depends_on:
      - "deep_thoughts_webserver"
